### ISSUE TITLE
Adding content

### ISSUE THREAD

**Issue by Leo-Aqua** [chvancooten/follina.py#22]
Is there a way to add content to docx/rtf file? Because after I've opened the file, added some content and saved it, it stoped working.

**Comment by chvancooten** [comment]
Hi @Leo-Aqua! Editing the content of the document is possible without affecting the operation of the exploit. Just make sure that you don't touch the (hardly visible) OLE object when you do so, since it is required for the exploit to work. If you want more granular control over your maldoc look at this gist: https://gist.github.com/tothi/66290a42896a97920055e50128c9f040
